// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"912","screenHeight":"624","changeWindowWidthTo":"912","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"off"}}
];
