// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"912","screenHeight":"624","changeWindowWidthTo":"912","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"off"}},
{"name":"pico-core","status":true,"description":"Tool for Event Making.","parameters":{}},
{"name":"pico-picture","status":true,"description":"Plugin Pictures for πco","parameters":{}},
{"name":"pico-mv","status":true,"description":"Add all of the MV commands as πco commands","parameters":{}}
];
